// Would get a better way to do this when time permits, This isn't sustainable

export const imageURLS = [
  'NO ID HAS AN INDEX OF ZERO',
  'https://i.imgur.com/SfoXrDf.png',
  'https://i.imgur.com/7yAhadt.png',
  'https://i.imgur.com/9LC4JGH.png',
  'https://i.imgur.com/8AEg0fK.png',
  'https://i.imgur.com/uecVpza.png',
  'https://i.imgur.com/fOVozwX.png',
  'https://i.imgur.com/O4wEyHF.png',
  'https://i.imgur.com/1KSVLo5.png',
  'https://i.imgur.com/tIiIiHu.png',
  'https://i.imgur.com/lsDvh17.png',
  'https://i.imgur.com/7OiZowP.png',
  'https://i.imgur.com/DmE4HTK.png',
];

export const description = [
  'NO ID HAS AN INDEX OF ZERO',
  `Our full-grain vegetable-tanned leather Duffle bag uses is unlined and has been designed with a pleated top to allow for easier access. Features include solid brass fixtures, including the compartment zip of the internal pocket. The Duffle comes with contrast leather handles pictured and reinforced leather shoulder strap.Please note variations in leather colour occur naturally between hide to hide. The leather on the bag will naturally have character and slight imperfections on the leather which we embrace.Please note that all our goods are made-to-order unless stock already exists in our shop in Melbourne. Lead times can be found in our footer below for leather goods and footwear.`,
  `Our full-grain vegetable-tanned leather Duffle bag uses is unlined and has been designed with a pleated top to allow for easier access. Features include solid brass fixtures, including the compartment zip of the internal pocket. The Duffle comes with contrast leather handles pictured and reinforced leather shoulder strap.Please note variations in leather colour occur naturally between hide to hide. The leather on the bag will naturally have character and slight imperfections on the leather which we embrace.Please note that all our goods are made-to-order unless stock already exists in our shop in Melbourne. Lead times can be found in our footer below for leather goods and footwear.`,
  `Our full-grain vegetable-tanned leather Duffle bag uses is unlined and has been designed with a pleated top to allow for easier access. Features include solid brass fixtures, including the compartment zip of the internal pocket. The Duffle comes with contrast leather handles pictured and reinforced leather shoulder strap.Please note variations in leather colour occur naturally between hide to hide. The leather on the bag will naturally have character and slight imperfections on the leather which we embrace.Please note that all our goods are made-to-order unless stock already exists in our shop in Melbourne. Lead times can be found in our footer below for leather goods and footwear.`,
  `Our full-grain vegetable-tanned leather Duffle bag uses is unlined and has been designed with a pleated top to allow for easier access. Features include solid brass fixtures, including the compartment zip of the internal pocket. The Duffle comes with contrast leather handles pictured and reinforced leather shoulder strap.Please note variations in leather colour occur naturally between hide to hide. The leather on the bag will naturally have character and slight imperfections on the leather which we embrace.Please note that all our goods are made-to-order unless stock already exists in our shop in Melbourne. Lead times can be found in our footer below for leather goods and footwear.`,
  `Our full-grain vegetable-tanned leather Duffle bag uses is unlined and has been designed with a pleated top to allow for easier access. Features include solid brass fixtures, including the compartment zip of the internal pocket. The Duffle comes with contrast leather handles pictured and reinforced leather shoulder strap.Please note variations in leather colour occur naturally between hide to hide. The leather on the bag will naturally have character and slight imperfections on the leather which we embrace.Please note that all our goods are made-to-order unless stock already exists in our shop in Melbourne. Lead times can be found in our footer below for leather goods and footwear.`,
  `Our full-grain vegetable-tanned leather Duffle bag uses is unlined and has been designed with a pleated top to allow for easier access. Features include solid brass fixtures, including the compartment zip of the internal pocket. The Duffle comes with contrast leather handles pictured and reinforced leather shoulder strap.Please note variations in leather colour occur naturally between hide to hide. The leather on the bag will naturally have character and slight imperfections on the leather which we embrace.Please note that all our goods are made-to-order unless stock already exists in our shop in Melbourne. Lead times can be found in our footer below for leather goods and footwear.`,
  `Our full-grain vegetable-tanned leather Duffle bag uses is unlined and has been designed with a pleated top to allow for easier access. Features include solid brass fixtures, including the compartment zip of the internal pocket. The Duffle comes with contrast leather handles pictured and reinforced leather shoulder strap.Please note variations in leather colour occur naturally between hide to hide. The leather on the bag will naturally have character and slight imperfections on the leather which we embrace.Please note that all our goods are made-to-order unless stock already exists in our shop in Melbourne. Lead times can be found in our footer below for leather goods and footwear.`,
  `Our full-grain vegetable-tanned leather Duffle bag uses is unlined and has been designed with a pleated top to allow for easier access. Features include solid brass fixtures, including the compartment zip of the internal pocket. The Duffle comes with contrast leather handles pictured and reinforced leather shoulder strap.Please note variations in leather colour occur naturally between hide to hide. The leather on the bag will naturally have character and slight imperfections on the leather which we embrace.Please note that all our goods are made-to-order unless stock already exists in our shop in Melbourne. Lead times can be found in our footer below for leather goods and footwear.`,
  `Our full-grain vegetable-tanned leather Duffle bag uses is unlined and has been designed with a pleated top to allow for easier access. Features include solid brass fixtures, including the compartment zip of the internal pocket. The Duffle comes with contrast leather handles pictured and reinforced leather shoulder strap.Please note variations in leather colour occur naturally between hide to hide. The leather on the bag will naturally have character and slight imperfections on the leather which we embrace.Please note that all our goods are made-to-order unless stock already exists in our shop in Melbourne. Lead times can be found in our footer below for leather goods and footwear.`,
  `Our full-grain vegetable-tanned leather Duffle bag uses is unlined and has been designed with a pleated top to allow for easier access. Features include solid brass fixtures, including the compartment zip of the internal pocket. The Duffle comes with contrast leather handles pictured and reinforced leather shoulder strap.Please note variations in leather colour occur naturally between hide to hide. The leather on the bag will naturally have character and slight imperfections on the leather which we embrace.Please note that all our goods are made-to-order unless stock already exists in our shop in Melbourne. Lead times can be found in our footer below for leather goods and footwear.`,
  `Our full-grain vegetable-tanned leather Duffle bag uses is unlined and has been designed with a pleated top to allow for easier access. Features include solid brass fixtures, including the compartment zip of the internal pocket. The Duffle comes with contrast leather handles pictured and reinforced leather shoulder strap.Please note variations in leather colour occur naturally between hide to hide. The leather on the bag will naturally have character and slight imperfections on the leather which we embrace.Please note that all our goods are made-to-order unless stock already exists in our shop in Melbourne. Lead times can be found in our footer below for leather goods and footwear.`,
  `Our full-grain vegetable-tanned leather Duffle bag uses is unlined and has been designed with a pleated top to allow for easier access. Features include solid brass fixtures, including the compartment zip of the internal pocket. The Duffle comes with contrast leather handles pictured and reinforced leather shoulder strap.Please note variations in leather colour occur naturally between hide to hide. The leather on the bag will naturally have character and slight imperfections on the leather which we embrace.Please note that all our goods are made-to-order unless stock already exists in our shop in Melbourne. Lead times can be found in our footer below for leather goods and footwear.`,
];
export const fitting = [
  'NO ID HAS AN INDEX OF ZERO',
  `Can work as a carry on bag for short flights (check with your flight provider) or to accompany you during your day-to-day business.54cm (length) x 34cm (width) x 34cm (height)`,
  `Can work as a carry on bag for short flights (check with your flight provider) or to accompany you during your day-to-day business.54cm (length) x 34cm (width) x 34cm (height)`,
  `Can work as a carry on bag for short flights (check with your flight provider) or to accompany you during your day-to-day business.54cm (length) x 34cm (width) x 34cm (height)`,
  `Can work as a carry on bag for short flights (check with your flight provider) or to accompany you during your day-to-day business.54cm (length) x 34cm (width) x 34cm (height)`,
  `Can work as a carry on bag for short flights (check with your flight provider) or to accompany you during your day-to-day business.54cm (length) x 34cm (width) x 34cm (height)`,
  `Can work as a carry on bag for short flights (check with your flight provider) or to accompany you during your day-to-day business.54cm (length) x 34cm (width) x 34cm (height)`,
  `Can work as a carry on bag for short flights (check with your flight provider) or to accompany you during your day-to-day business.54cm (length) x 34cm (width) x 34cm (height)`,
  `Can work as a carry on bag for short flights (check with your flight provider) or to accompany you during your day-to-day business.54cm (length) x 34cm (width) x 34cm (height)`,
  `Can work as a carry on bag for short flights (check with your flight provider) or to accompany you during your day-to-day business.54cm (length) x 34cm (width) x 34cm (height)`,
  `Can work as a carry on bag for short flights (check with your flight provider) or to accompany you during your day-to-day business.54cm (length) x 34cm (width) x 34cm (height)`,
  `Can work as a carry on bag for short flights (check with your flight provider) or to accompany you during your day-to-day business.54cm (length) x 34cm (width) x 34cm (height)`,
  `Can work as a carry on bag for short flights (check with your flight provider) or to accompany you during your day-to-day business.54cm (length) x 34cm (width) x 34cm (height)`,
];
