CREATE TABLE products (
id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
name varchar(80) NOT NULL,
title varchar(100) NOT NULL,
quantity integer,
description varchar(300),
price integer,
fitting varchar(200),
color_choice varchar(20),
image varchar(100)
);


INSERT INTO products
(name, title, quantity, description, price, fitting, color_choice, image)
VALUES
('Branded Leather Bag1', 'This Product is loving', 0, 'dscr', 299, 'ft', '', 'https://i.imgur.com/h5cWFHC.jpg'),
('Branded Leather Bag2', 'This Product is loving', 0, 'dscr', 199, 'ft', '', 'https://i.imgur.com/h5cWFHC.jpg'),
('Branded Leather Bag3', 'This Product is loving', 0, 'dscr', 99, 'ft', '', 'https://i.imgur.com/h5cWFHC.jpg'),
('Branded Leather Bag4', 'This Product is loving', 0, 'dscr', 170, 'ft', '', 'https://i.imgur.com/oSvYCl9m.jpg'),
('Branded Leather Bag5', 'This Product is loving', 0, 'dscr', 139, 'ft', '', 'https://i.imgur.com/G3ZWEv4m.jpg'),
('Branded Leather Bag6', 'This Product is loving', 0, 'dscr', 219, 'ft', '', 'https://i.imgur.com/h5cWFHC.jpg'),
('Branded Leather Bag7', 'This Product is loving', 0, 'dscr', 254, 'ft', '', 'https://i.imgur.com/h5cWFHC.jpg'),
('Branded Leather Bag8', 'This Product is loving', 0, 'dscr', 292, 'ft', '', 'https://i.imgur.com/h5cWFHC.jpg'),
('Branded Leather Bag9', 'This Product is loving', 0, 'dscr', 419, 'ft', '', 'https://i.imgur.com/h5cWFHC.jpg'),
('Branded Leather Bag10', 'This Product is loving', 0, 'dscr', 319, 'ft', '', 'https://i.imgur.com/h5cWFHC.jpg');




INSERT INTO products
(name, title, quantity, description, price, fitting, color_choice, image)
VALUES
('Branded Leather Bag11', 'This Product is loving', 0, 'dscr', 619, 'ft', '', 'https://i.imgur.com/oSvYCl9m.jpg'),
('Branded Leather Bag12', 'This Product is loving', 0, 'dscr', 69, 'ft', '', 'https://i.imgur.com/oSvYCl9m.jpg');
